[package]
name = "configurator-java"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["cdylib"]

[dependencies]
configurator-rs = { path = "../configurator-rs/" }
jni = "0.19.0"
