[package]
name = "configurator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"
toml = "0.5.8"
